version: '3.5'
services:
  flask-app:
    build: .
    container_name: calendar-app
    ports:
      - "5000:5000"
    volumes:
      - ./db:/app/db
    environment:
      FLASK_ENV: development 